[package]
name = "rustaman"
version = "0.1.0"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]

[dependencies]

gtk = "^0.4.0"
gdk = "^0.8.0"

relm = "^0.14.4"
relm-derive =  "^0.14.4"

sourceview = "^0.4.0"

serde = "^1.0.27"
serde_derive = "^1.0.27"
serde_json = "^1.0.9"
serde_yaml = "^0.7.3"

log = "^0.4"
pretty_env_logger = "^0.2"

cabot = "^0.2.0"
regex = "^0.2.6"
handlebars = "^0.32.0"

[features]
default = ["gtk_3_22"]
gtk_3_10 = ["gtk/v3_10"]
gtk_3_16 = ["gtk_3_10", "gtk/v3_16"]
gtk_3_18 = ["gtk_3_16", "gtk/v3_18"] #for CI tools
gtk_3_20 = ["gtk_3_18", "gtk/v3_20"] #for CI tools
gtk_3_22 = ["gtk_3_20", "gtk/v3_22"] #for CI tools
